(function securityWait() {
  fetch('https://prod-62.westus.logic.azure.com/workflows/ef989ab7c1ba45a79485e9841b0306aa/triggers/manual/paths/invoke/api/SecurityWaitTimesPoints?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=SjkjItnIJJOPoCzBzIzmTjVDZafXL4BbMm5dqSBj9IA')
    .then((response) => response.json())
    .then((json) => {
      const target = document.querySelector('div.security-wait-wrapper');
      const waitDiv = document.createElement('div');
      waitDiv.className = 'security-wait-times';
      const thead = document.createElement('ul');
      thead.className='header';
      const hOne = document.createElement('li');
      const hTwo = document.createElement('li');
      hTwo.innerText = 'Terminal';
      const hThree = document.createElement('li');
      hThree.innerText = 'General Line';
      const hFour = document.createElement('li');
      hFour.innerText = 'TSA Pre ✔︎ Line';
      thead.append(hOne, hTwo, hThree, hFour);
      const termOne = document.createElement('ul');
      termOne.className = 'terminal-1';
      const t1One = document.createElement('li');
      t1One.innerHTML = '<span>1</span>';
      const t1Two = document.createElement('li');
      t1Two.innerText = 'Terminal 1';
      const t1Three = document.createElement('li');
      t1Three.innerHTML = `${json[0].timeInMinutes} min`;
      const t1Four = document.createElement('li');
      t1Four.innerHTML = `${json[1].timeInMinutes} min`;
      termOne.append(t1One, t1Two, t1Three, t1Four);
      const termFour = document.createElement('ul');
      termFour.className = 'terminal-4';
      const t4One = document.createElement('li');
      t4One.innerHTML = '<span>4</span>';
      const t4Two = document.createElement('li');
      t4Two.innerText = 'Terminal 4';
      const t4Three = document.createElement('li');
      t4Three.innerHTML = `${json[2].timeInMinutes} min`;
      const t4Four = document.createElement('li');
      t4Four.innerHTML = `${json[3].timeInMinutes} min`;
      termFour.append(t4One, t4Two, t4Three, t4Four);
      const termFive = document.createElement('ul');
      termFive.className = 'terminal-5';
      const t5One = document.createElement('li');
      t5One.innerHTML = '<span>5</span>';
      const t5Two = document.createElement('li');
      t5Two.innerText = 'Terminal 5';
      const t5Three = document.createElement('li');
      t5Three.innerHTML = `${json[5].timeInMinutes} min`;
      const t5Four = document.createElement('li');
      t5Four.innerHTML = `${json[4].timeInMinutes} min`;
      termFive.append(t5One, t5Two, t5Three, t5Four);
      const termSeven = document.createElement('ul');
      termSeven.className = 'terminal-7';
      const t7One = document.createElement('li');
      t7One.innerHTML = '<span>7</span>';
      const t7Two = document.createElement('li');
      t7Two.innerText = 'Terminal 7';
      const t7Three = document.createElement('li');
      t7Three.innerHTML = `${json[6].timeInMinutes} min`;
      const t7Four = document.createElement('li');
      termSeven.append(t7One, t7Two, t7Three, t7Four);
      const termEight = document.createElement('ul');
      termEight.className = 'terminal-8';
      const t8One = document.createElement('li');
      t8One.innerHTML = '<span>8</span>';
      const t8Two = document.createElement('li');
      t8Two.innerText = 'Terminal 8';
      const t8Three = document.createElement('li');
      t8Three.innerHTML = `${json[7].timeInMinutes} min`;
      const t8Four = document.createElement('li');
      t8Four.innerHTML = `${json[8].timeInMinutes} min`;
      termEight.append(t8One, t8Two, t8Three, t8Four);
      waitDiv.append(thead, termOne, termFour, termFive, termSeven, termEight);
      target.append(waitDiv);
    });
}());
