(function cityForm() {
  const target = document.querySelector('div.city-form-wrapper');
  const form = document.createElement('form');
  const airlineWrapper = document.createElement('div');
  const flightNumberWrapper = document.createElement('div');
  const dateWrapper = document.createElement('div');
  const buttonWrapper = document.createElement('div');
  buttonWrapper.className = 'button-wrapper';
  const airlineField = document.createElement('input');
  airlineField.id = 'Airport';
  const airlineFieldLabel = document.createElement('label');
  airlineFieldLabel.setAttribute('for', 'Airport');
  airlineFieldLabel.innerText = 'Departure Airport';
  const flightNumberField = document.createElement('input');
  flightNumberField.id = 'Arrival';
  const flightNumberFieldLabel = document.createElement('label');
  flightNumberFieldLabel.setAttribute('for', 'Arrival');
  flightNumberFieldLabel.innerText = 'Arrival Airport';
  const dateField = document.createElement('input');
  dateField.id = 'Date';
  const dateFieldLabel = document.createElement('label');
  dateFieldLabel.setAttribute('for', 'Date');
  dateFieldLabel.innerText = 'Date';
  const submitButton = document.createElement('input');
  submitButton.setAttribute('type', 'button');
  submitButton.value = 'Track Flight';
  const allButton = document.createElement('input');
  allButton.setAttribute('type', 'button');
  allButton.value = 'All Flights';
  buttonWrapper.append(submitButton, allButton);
  airlineWrapper.append(airlineField, airlineFieldLabel);
  flightNumberWrapper.append(flightNumberField, flightNumberFieldLabel);
  dateWrapper.append(dateField, dateFieldLabel);
  form.append(airlineWrapper, flightNumberWrapper, dateWrapper, buttonWrapper);
  target.append(form);
}());
