(function cityForm() {
  const target = document.querySelector('div.book-parking-wrapper');
  const form = document.createElement('form');
  form.className = 'book-parking';
  const entry = document.createElement('div');
  const exit = document.createElement('div');
  const entryDate = document.createElement('div');
  const entryTime = document.createElement('div');
  const entryDateField = document.createElement('input');
  const entryDateLabel = document.createElement('label');
  entryDateField.setAttribute('placeholder', 'Select Date');
  entryDateField.setAttribute('required', 'required');
  entryDateLabel.innerText = 'Entry Date';
  const entryTimeField = document.createElement('input');
  const entryTimeLabel = document.createElement('label');
  entryTimeField.setAttribute('placeholder', 'Select Time');
  entryTimeField.setAttribute('required', 'required');
  entryTimeLabel.innerText = 'Entry Time';
  entryDate.append(entryDateLabel, entryDateField);
  entryTime.append(entryTimeLabel, entryTimeField);
  entry.append(entryDate, entryTime);
  const exitDate = document.createElement('div');
  const exitTime = document.createElement('div');
  const exitDateField = document.createElement('input');
  const exitDateLabel = document.createElement('label');
  exitDateField.setAttribute('placeholder', 'Select Date');
  exitDateField.setAttribute('required', 'required');
  exitDateLabel.innerText = 'Exit Date';
  const exitTimeField = document.createElement('input');
  const exitTimeLabel = document.createElement('label');
  exitTimeField.setAttribute('placeholder', 'Select Time');
  exitTimeField.setAttribute('required', 'required');
  exitTimeLabel.innerText = 'Exit Time';
  exitDate.append(exitDateLabel, exitDateField);
  exitTime.append(exitTimeLabel, exitTimeField);
  exit.append(exitDate, exitTime);
  const terminal = document.createElement('div');
  const terminalField = document.createElement('input');
  const terminalLabel = document.createElement('label');
  terminalField.setAttribute('placeholder', 'Please Select');
  terminalLabel.innerText = 'Terminal';
  terminal.append(terminalLabel, terminalField);
  const submit = document.createElement('input');
  submit.setAttribute('type', 'button');
  submit.value = 'Book Now';
  form.append(entry, exit, terminal, submit);
  target.replaceWith(form);
}());
