(function() {
  const target = document.querySelector('div.flight-form-wrapper');
  const form = document.createElement('form');
  const airlineWrapper = document.createElement('div');
  const flightNumberWrapper = document.createElement('div');
  const dateWrapper = document.createElement('div');
  const buttonWrapper = document.createElement('div');
  buttonWrapper.className = 'button-wrapper';
  const airlineField = document.createElement('input');
  airlineField.id='Airlines';
  const airlineFieldLabel = document.createElement('label');
  airlineFieldLabel.setAttribute('for', 'Airlines');
  airlineFieldLabel.innerText = "Airline";
  const flightNumberField = document.createElement('input');
  flightNumberField.id='Flight-Number';
  const flightNumberFieldLabel = document.createElement('label');
  flightNumberFieldLabel.setAttribute('for', 'Flight-Number');
  flightNumberFieldLabel.innerText = "Flight Number";
  const dateField = document.createElement('input');
  dateField.id='Date';
  const dateFieldLabel = document.createElement('label');
  dateFieldLabel.setAttribute('for', 'Date');
  dateFieldLabel.innerText = 'Date';
  const submitButton = document.createElement('input');
  submitButton.setAttribute('type', 'button');
  submitButton.value = 'Track Flight';
  const allButton = document.createElement('input');
  allButton.setAttribute('type', 'button');
  allButton.value = 'All Flights';
  buttonWrapper.append(submitButton, allButton);
  airlineWrapper.append(airlineField, airlineFieldLabel);
  flightNumberWrapper.append(flightNumberField, flightNumberFieldLabel);
  dateWrapper.append(dateField, dateFieldLabel);
  form.append(airlineWrapper, flightNumberWrapper, dateWrapper, buttonWrapper);
  target.append(form);
})();
